// DATA - API REQUEST
export const REQUEST_ARTISTS = 'REQUEST_ARTISTS'
export const RECEIVE_ARTISTS = 'RECEIVE_ARTISTS'
export const REQUEST_NUMBER_OF_ARTISTS = 'REQUEST_NUMBER_OF_ARTISTS'
export const RECEIVE_NUMBER_OF_ARTISTS = 'RECEIVE_NUMBER_OF_ARTISTS'

export const REQUEST_ARTIST = 'REQUEST_ARTIST'
export const RECEIVE_ARTIST = 'RECEIVE_ARTIST'

export const REQUEST_MANGAS = 'REQUEST_MANGAS'
export const RECEIVE_MANGAS = 'RECEIVE_MANGAS'
export const REQUEST_NUMBER_OF_MANGAS = 'REQUEST_NUMBER_OF_MANGAS'
export const RECEIVE_NUMBER_OF_MANGAS = 'RECEIVE_NUMBER_OF_MANGAS'

export const REQUEST_MANGA = 'REQUEST_MANGA'
export const RECEIVE_MANGA = 'RECEIVE_MANGA'

export const REQUEST_VOLUMES = 'REQUEST_VOLUMES'
export const RECEIVE_VOLUMES = 'RECEIVE_VOLUMES'
export const REQUEST_NUMBER_OF_VOLUMES = 'REQUEST_NUMBER_OF_VOLUMES'
export const RECEIVE_NUMBER_OF_VOLUMES = 'RECEIVE_NUMBER_OF_VOLUMES'

export const REQUEST_CHAPTERS = 'REQUEST_CHAPTERS'
export const RECEIVE_CHAPTERS = 'RECEIVE_CHAPTERS'
export const REQUEST_NUMBER_OF_CHAPTERS = 'REQUEST_NUMBER_OF_CHAPTERS'
export const RECEIVE_NUMBER_OF_CHAPTERS = 'RECEIVE_NUMBER_OF_CHAPTERS'

export const REQUEST_CHAPTER = 'REQUEST_CHAPTER'
export const RECEIVE_CHAPTER = 'RECEIVE_CHAPTER'

export const REQUEST_IMAGES = 'REQUEST_IMAGES'
export const RECEIVE_IMAGES = 'RECEIVE_IMAGES'
export const REQUEST_NUMBER_OF_IMAGES = 'REQUEST_NUMBER_OF_IMAGES'
export const RECEIVE_NUMBER_OF_IMAGES = 'RECEIVE_NUMBER_OF_IMAGES'

// UI
export const SET_BREADCRUMB = 'SET_BREADCRUMB'
export const SET_THEME = 'SET_THEME'
export const SET_STYLE = 'SET_STYLE'
